hfa_terraform_state_bucket     = "hfa-terraform-state-test"
hfa_iam_state_key              = "hfa-iam/terraform.tfstate"
hfa_network_state_key          = "hfa-network/terraform.tfstate"
hfa_network_workload_state_key = "hfa-network-workloads/terraform.tfstate"
hfa_app_state_key              = "hfa-app/terraform.tfstate"
hfa_terraform_state_region     = "ap-southeast-3"
hfa_default_region             = "ap-southeast-3"