hfa_security_account_name  = "hwstaff_intl_lab_01_security"
hfa_iam_account_name       = "hwstaff_intl_lab_01_iam"
hfa_transit_account_name   = "hwstaff_intl_lab_01_transit"
hfa_common_account_name    = "hwstaff_intl_lab_01_common"
hfa_app_account_name       = "hwstaff_intl_lab_01_app"
hfa_terraform_state_bucket = "terraform-state-singapore"