hfa_security_account_name  = "hwstaff_intl_lab_02_security"
hfa_iam_account_name       = "hwstaff_intl_lab_02_iam"
hfa_transit_account_name   = "hwstaff_intl_lab_02_transit"
hfa_common_account_name    = "hwstaff_intl_lab_02_common"
hfa_app_account_name       = "hwstaff_intl_02_app"
hfa_terraform_state_bucket = "hfa-terraform-state-now"