hfa_app_prod_cidr             = "10.20.0.0/16"
hfa_common_prod_cidr          = "10.21.0.0/16"
hfa_terraform_state_bucket    = "hfa-terraform-state-test"
hfa_iam_state_key             = "hfa-iam/terraform.tfstate"
hfa_network_state_key         = "hfa-network/terraform.tfstate"
hfa_terraform_state_region    = "ap-southeast-3"