HFA_Security_OBS_Bucket_Name = "hfa-security-log-archive124"
hfa_terraform_state_bucket   = "hfa-terraform-state"
hfa_iam_state_key            = "hfa-iam/terraform.tfstate"
hfa_terraform_state_region   = "ap-southeast-3"
hfa_cts_notification_email_address = "mujianmin1@huawei.com"